env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
  - import
rules:
  'react/jsx-filename-extension':
    - 2
    - 'extensions': ['.js', '.jsx', '.ts', '.tsx']
  'jsx-a11y/label-has-associated-control': 0
settings:
  'import/resolver':
    'typescript':
      'alwaysTryTypes': true
      'project': './tsconfig.json'
